name: Build and test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/jobs-build.yml

  test:
    uses: ./.github/workflows/jobs-test.yml
    needs: [build]
