name: jobs/build

on:
  workflow_call:

env:
  ADDON_DIR: addons/godot-rapier-3d
  RUST_DIR: addons/godot-rapier-3d/rust
  BIN_DIR: addons/godot-rapier-3d/bin

jobs:
  build_single:
    name: Build - ${{ matrix.release_for }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # - release_for: linux-32-gnu
          #   runner: ubuntu-latest
          #   target: i686-unknown-linux-gnu
          #   compiler: cross
          #   archive: linux-gnu-x86_32
          #   archive_ext: .tar.gz
          #   bin: libgodot_rapier_3d.so

          - release_for: linux-64-gnu
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            compiler: cross
            archive: linux-gnu-x86_64
            archive_ext: .tar.gz
            bin: libgodot_rapier_3d.so

          # - release_for: linux-64-arm
          #   runner: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   compiler: cross
          #   archive: linux-arm-x86_64
          #   archive_ext: .tar.gz
          #   bin: libgodot_rapier_3d.so

          # - release_for: linux-64-rv
          #   runner: ubuntu-latest
          #   target: riscv64gc-unknown-linux-gnu
          #   compiler: cross
          #   archive: linux-rv-x86_64
          #   archive_ext: .tar.gz
          #   bin: libgodot_rapier_3d.so

          # - release_for: windows-32-msvc
          #   runner: windows-latest
          #   target: i686-pc-windows-msvc
          #   compiler: cross
          #   archive: windows-msvc-x86_32
          #   archive_ext: .zip
          #   bin: godot_rapier_3d.dll

          - release_for: windows-64-msvc
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            compiler: cross
            archive: windows-msvc-x86_64
            archive_ext: .zip
            bin: godot_rapier_3d.dll

          # - release_for: macos-amd64
          #   runner: macos-latest
          #   target: x86_64-apple-darwin
          #   compiler: cross
          #   bin: libgodot_rapier_3d.dylib
          #   archive: macos-amd-x86_64
          #   archive_ext: .tar.gz

          # - release_for: macos-arm64
          #   runner: macos-latest
          #   target: aarch64-apple-darwin
          #   compiler: cross
          #   bin: libgodot_rapier_3d.dylib
          #   archive: macos-arm-x86_64
          #   archive_ext: .tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        if: matrix.compiler == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
        working-directory: ${{ env.RUST_DIR }}

      - name: Build rust binary
        run: ${{ matrix.compiler }} build --verbose --locked --release --target ${{ matrix.target }}
        working-directory: ${{ env.RUST_DIR }}

      - name: Move rust binary
        shell: bash
        run: |
          mkdir ${{ env.BIN_DIR }}
          mv ${{ env.RUST_DIR }}/target/${{ matrix.target }}/release/${{ matrix.bin }} ${{ env.BIN_DIR }}/${{ matrix.target }}-${{ matrix.bin }}

      - name: Replace .gdextension config
        shell: bash
        run: |
          rm godot-rapier-3d.gdextension
          mv godot-rapier-3d.gdext.dist godot-rapier-3d.gdextension

      - name: Add VERSION.txt
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          ${{ env.VERSION }} > ${{ env.ADDON_DIR }}/VERSION.txt

      - name: Copy LICENSE.txt
        shell: bash
        run: cp LICENSE.txt ${{ env.ADDON_DIR }}

      - name: Package as archive
        shell: bash
        run: |
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            7z a godot-rapier-3d--${{ matrix.archive }}${{ matrix.archive_ext }} -xr!rust ./addons/
            7z a godot-rapier-3d--${{ matrix.archive }}${{ matrix.archive_ext }} godot-rapier-3d.gdextension
            7z l godot-rapier-3d--${{ matrix.archive }}${{ matrix.archive_ext }}
          else
            tar czvf godot-rapier-3d--${{ matrix.archive }}${{ matrix.archive_ext }} --exclude=rust ./addons/godot-rapier-3d/ godot-rapier-3d.gdextension
            tar ztvf godot-rapier-3d--${{ matrix.archive }}${{ matrix.archive_ext }}
          fi

      - name: Upload rust binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: gr3d-rust-binary-${{ matrix.release_for }}
          path: "${{ env.BIN_DIR }}/*godot_rapier_3d*"

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-3d--${{ matrix.archive }}${{ matrix.archive_ext }}
          path: "godot-rapier-3d-*"

      - name: List dirs
        shell: bash
        run: |
          pwd
          echo 'ls -la ./'
          ls -la ./
          echo ---
          echo 'ls -la ${{ env.RUST_DIR }}'
          ls -la ${{ env.RUST_DIR }}
          echo ---
          echo 'ls -la ${{ env.ADDON_DIR }}'
          ls -la ${{ env.ADDON_DIR }}
        if: always()

  # ---

  build_all:
    name: Build all (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    needs: build_single
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            ext: .tar.gz
          - runner: windows-latest
            ext: .zip

    steps:
      - uses: actions/checkout@v4

      - name: Download all rust binary artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: gr3d-rust-binary-*
          path: ${{ env.BIN_DIR }}

      - name: Replace .gdextension config
        shell: bash
        run: |
          rm godot-rapier-3d.gdextension
          mv godot-rapier-3d.gdext.dist godot-rapier-3d.gdextension

      - name: Add VERSION.txt
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          ${{ env.VERSION }} > ${{ env.ADDON_DIR }}/VERSION.txt

      - name: Copy LICENSE.txt
        shell: bash
        run: cp LICENSE.txt ${{ env.ADDON_DIR }}

      - name: Package as archive
        shell: bash
        run: |
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            7z a godot-rapier-3d--all${{ matrix.ext }} -xr!rust ./addons/
            7z a godot-rapier-3d--all${{ matrix.ext }} -xr!rust godot-rapier-3d.gdextension
          else
            tar czvf godot-rapier-3d--all${{ matrix.ext }} --exclude=rust ./addons/godot-rapier-3d/ godot-rapier-3d.gdextension
          fi

      - name: Upload all package artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-rapier-3d--all${{ matrix.ext }}
          path: "godot-rapier-3d--all${{ matrix.ext }}"

      - name: List dirs
        shell: bash
        run: |
          pwd
          echo 'ls -la ./'
          ls -la ./
          echo ---
          echo 'ls -la ${{ env.RUST_DIR }}'
          ls -la ${{ env.RUST_DIR }}
          echo ---
          echo 'ls -la ${{ env.ADDON_DIR }}'
          ls -la ${{ env.ADDON_DIR }}
          echo ---
          echo 'ls -la ${{ env.BIN_DIR }}'
          ls -la ${{ env.BIN_DIR }}
        if: always()
