name: jobs/release

on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1 # https://bun.sh/guides/runtime/cicd

      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: godot-rapier-3d-*

      - name: Download determinism diffs
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: determinism-diffs*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            godot-rapier-3d-*
            determinism-diffs.zip
          generate_release_notes: true

      - name: bun ci/debug.ts
        shell: bash
        run: bun ci/debug.ts
        if: always()
