name: Main

on:
  workflow_dispatch:
  push:
    paths:
      - "addons/godot-rapier-3d/**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Regex for a version number such as v0.2.1

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]

  release:
    uses: ./.github/workflows/release.yml
    needs: [build, test]
